######################################################################
# Automatically generated by qmake (2.01a) to 26. mai 00:01:48 2011
######################################################################

TEMPLATE = app
TARGET = gpxhrm
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    gpxparser.cpp \
    hrmparser.cpp

CONFIG += console

HEADERS += \
    gpxparser.h \
    hrmparser.h